j0k3r/graby

.gitignore
README.md
composer.json
composer.lock
src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php

Just a replacement for the built-in `debug()` method

Add logger

---

README.md
src/Graby.php
tests/GrabyTest.php

Return content type

---

composer.json
composer.lock
src/Extractor/ContentExtractor.php
src/Graby.php
src/Ring/Client/SafeCurlHandler.php
tests/GrabyTest.php
tests/Ring/Client/SafeCurlHandlerTest.php

Should fix #7.
@freddyb Are you ok with that patch ?

Handle Safecurl

---

README.md
src/Graby.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyTest.php
tests/fixtures/sites/blogger.test
tests/fixtures/sites/lemonde.test

Return language of the url

---

src/Graby.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyTest.php
tests/fixtures/site_config/multiplepage1.com.txt

Plain text

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

Handle ng-controller as ajax_triggers

---

src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php
tests/SiteConfig/ConfigBuilderTest.php

Could be useful when integrate it in Symfony 2 as a service, for example.

Ability to re-define logger

---

src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/GrabyTest.php
tests/SiteConfig/ConfigBuilderTest.php
tests/fixtures/sites/blogger.test
tests/fixtures/sites/lemonde.test

Main goal is to increase the Scrutinizer note & code coverage.
- Refactorize
- "return early"
- Avoid code duplication

Trying to cleanup the _old_ code

---

README.md
src/Extractor/HttpClient.php
src/Graby.php
tests/Extractor/HttpClientTest.php

- Add a timeout on each request (10s)
- Avoid endless redirects (10 redirects)

Timeout redirects

---

README.md
src/Graby.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php

Add a default title when no title are found

---

composer.json
src/Graby.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php

I did NOT wanted to handle accent in user, password & query string for now. As it'll require more loop & checks.
Should fix #44 & https://github.com/wallabag/wallabag/issues/1235

Handle accent in host & path

---

src/Extractor/ContentExtractor.php
src/Graby.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php

Handle spaces in URL to avoid unnecessary 404.
Related to: https://github.com/wallabag/wallabag/issues/2188

Handle space in url

---

.travis.yml
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/GrabyTest.php

Fix https://github.com/j0k3r/graby/issues/53

Handle ZIP files

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

For example, here: https://munchies.vice.com/fr/articles/plongee-dans-le-monde-sibyllin-des-enseignes-de-kebabs

Support lazy-load image from Vice

---

src/Extractor/HttpClient.php
src/Graby.php
tests/Extractor/HttpClientTest.php
tests/GrabyTest.php

Might fix https://github.com/j0k3r/graby/issues/69

Absolute preview

---

src/Extractor/HttpClient.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/GrabyTest.php

Fix https://github.com/wallabag/wallabag/issues/2796

Fix urlencoded header

---

README.md
src/Extractor/ContentExtractor.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php
tests/fixtures/site_config/nativead.io.txt

Should fix https://github.com/j0k3r/graby/issues/75

Add support for native_ad_clue

---

README.md
src/Extractor/ContentExtractor.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php
tests/fixtures/sites/blogger.test
tests/fixtures/sites/lemonde.test

Fix https://github.com/j0k3r/graby/issues/79
Like previously authors will be an array

Extract author

---

src/Extractor/HttpClient.php
src/Graby.php
tests/GrabyTest.php

In case if we failed to retrieve it from the content.
Fix https://github.com/j0k3r/graby/issues/85

Retrieve language from header

---

src/Graby.php
tests/GrabyTest.php
tests/fixtures/malformed_UTF8_characters.txt

when the body is serialized, the data could not be encoded
because it contains invalid UTF8 characters.
@see https://github.com/wallabag/wallabag/issues/3154

Fix utf8 encoding for plain text page

---

composer.json
src/Graby.php
tests/GrabyFunctionalTest.php

But use the dev-master requirement since the 1.2 isn’t publised on packagist yet. See https://github.com/kesar/HTMLawed/pull/15
This should fix https://github.com/j0k3r/graby/issues/111

Jump to HTMLawed 1.2

---

composer.json
src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php

- Update smalot/pdfparser deps to allow < 1.0.0
- Fix tests because global rules got a find_string & replace_string so they can't be empty anymore

Update pdf deps

---

tests/GrabyFunctionalTest.php
tests/GrabyTest.php

Require tidy extension for tests

---

README.md

Following discussion here: https://github.com/j0k3r/graby/pull/130
Poke @Kdecherf

Add a small message about Tidy

---

.gitattributes
.scrutinizer.yml
src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/Ring/Client/SafeCurlHandlerTest.php
tests/SiteConfig/ConfigBuilderTest.php

And add some message to assertion

Remove unused $res

---

.travis.yml
composer.json

Re-use coveralls instead of Scrutinizer.

Re-use coveralls

---

src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php
tests/SiteConfig/ConfigBuilderTest.php

This allow to define the image attributes replacement for lazyloaded image.
For example https://github.com/fivefilters/ftr-site-config/pull/403

Add `src_lazy_load_attr` in siteconfig

---

src/Graby.php
tests/GrabyTest.php
tests/fixtures/sites/framablog.test

Just as I told you, this is the way I found to avoid empty node being fetched. It can fix issues like [this one](https://github.com/wallabag/wallabag/issues/3455). If you have a better idea, let me know.
Have a nice day.

Empty nodes removed (related to wallabag #3455)

---

src/Graby.php
tests/GrabyTest.php

Following https://github.com/j0k3r/graby/pull/141

Cleanup after latest PR

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

We can use the `name` from the JsonLd (https://schema.org/VideoObject). Not sure about `headline` pertinence as a title.

Use of name from JsonLd as title

---

composer.json

Following https://github.com/j0k3r/graby/pull/172

Adding missing cookie parser

---

.travis.yml
tests/GrabyFunctionalTest.php
tests/fixtures/sites/lemonde.test

- Remove `sudo: false` to use the new Travis infra
- Add a build for PHP 7.3
- Drop HHVM support

New travis infra

---

src/Extractor/HttpClient.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/HttpClientTest.php

Add “Accept” http_header in site_config

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

Avoid json-ld date to be an array

---

phpstan.neon
phpunit.xml
src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php
tests/SiteConfig/ConfigBuilderTest.php

- Better iframe detection
- Better element removing when it's an attribute

Applied some changes from Full-Text RSS

---

src/Extractor/ContentExtractor.php

See https://github.com/fivefilters/ftr-site-config/pull/666

Add `data-srcset` as lazyload attributes

---

src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyTest.php

Hi there,
That can fix some JSON LD with multiple authors like the one from [lemonde.fr](https://www.lemonde.fr/blog/huet/2019/10/18/nucleaire-une-saisine-parlementaire-sur-astrid/).
I did a boyscout to fix the tests. Hope this is ok.
Have a nice day.

JSON LD multiple authors

---

phpstan.neon
phpunit.xml
src/Extractor/HttpClient.php

PHPUnit 8 require PHP >= 7.2
Graby require PHP >= 7.1

Lock to PHPUnit 7

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

Fix https://github.com/wallabag/wallabag/issues/4330

Add support for refresh header

---

composer.json

also updated the site-config repo to use sf5 finder

Allow Symfony 5 installation

---

.scrutinizer.yml
.travis.yml

Use new Scrutinizer engine

---

tests/GrabyFunctionalTest.php

I updated the test case but I was wondering why you were fetching real site instead of using existing fixture?

Fix test case with real content (bjori site updated)

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

Hi there,
Fix a case where an empty attribute were overriding a filled in one.
Have a nice day and stay safe.

Case where an attribute is empty overriding a filled in value

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
tests/Extractor/HttpClientTest.php
tests/Monolog/Formatter/GrabyFormatterTest.php
tests/Monolog/Handler/GrabyHandlerTest.php

Also use ubuntu-20.04 instead of 18-04

Fix PHPStan

---

composer.json
phpunit.xml
src/Graby.php
src/HttpClient/Plugin/CookiePlugin.php

Fix https://github.com/j0k3r/graby/issues/265
And better fix for https://github.com/j0k3r/graby/issues/236

Add custom cookie plugin to reject bad cookie

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
composer.json
phpstan.neon
phpunit.xml
src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/HttpClient/Plugin/CookiePlugin.php
src/HttpClient/Plugin/History.php
src/Monolog/Handler/GrabyHandler.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php

Also:
- test PHP 8.1
- update to PHPStan@1
- allow symfony/* 6.0
- drop PHP < 7.4

Type everything

---

src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/HttpClient/Plugin/CookiePlugin.php
src/HttpClient/Plugin/History.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php

Thanks to @jtojnar in https://github.com/j0k3r/graby/pull/282
Also:
- cast some variable to improve PHPStan
- catch `JsonException` when parsing JSON-LD

Code update thanks to Rector

---

composer.json
src/Extractor/ContentExtractorConfig.php
tests/Extractor/ContentExtractorTest.php

See https://github.com/fivefilters/ftr-site-config/pull/928

Add `ippen.media` fingerprint

---

composer.json
src/Graby.php
tests/GrabyFunctionalTest.php

Because it's no more maintained.

Replace `true/punycode` by `symfony/polyfill-intl-idn`

---

.php-cs-fixer.php
composer.json
maintenance/Rector/MockGrabyResponseRector.php
src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/HttpClient/Plugin/CookiePlugin.php
src/OptionsResolver/ArrayStringOptionsTrait.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/SiteConfig/ConfigBuilderTest.php

- Use PHP 8 functions
- Apply PHP-CS-Fixer fixes
- Apply Rector fixes
The custom rector rule is currently broken https://github.com/rectorphp/rector/issues/7950

Fix coding style for PHP-CS-Fixer 3.17.0

---

src/Extractor/ContentExtractor.php

ContentExtractor: Make $node a required parameter

---

.php-cs-fixer.php
maintenance/Rector/MockGrabyResponseRector.php
phpstan.neon
src/Extractor/ContentExtractor.php
src/Extractor/ContentExtractorConfig.php
src/Extractor/HttpClient.php
src/Extractor/HttpClientConfig.php
src/Graby.php
src/GrabyConfig.php
src/Monolog/Formatter/GrabyFormatter.php
src/Monolog/Handler/GrabyHandler.php
src/OptionsResolver/ArrayStringOptionsTrait.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/ConfigBuilderConfig.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php
tests/SiteConfig/ConfigBuilderTest.php

Now only the `JSLikeHTMLElement` issues remain.
Depends on https://github.com/j0k3r/graby/pull/353

PHPStan fixes

---

.github/workflows/continuous-integration.yml

(cherry picked from commit 38976e3839fa3a5261c10b8c8780f6b99747ca75)

[2.x] ci: Add PHP 8.4

---

composer.json
maintenance/Rector/MockGrabyResponseRector.php
maintenance/phpstan-baseline-lt-8.0.neon
maintenance/phpstan-ignore-by-php-version.php
maintenance/rector.php
phpstan.dist.neon
src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/SiteConfig/ConfigBuilderTest.php

https://github.com/phpstan/phpstan/blob/2.1.x/UPGRADING.md
Also had to bump Rector since it uses PHPStan internally.
https://github.com/rectorphp/rector/releases/tag/2.0.0

Upgrade to PHPStan 2.0

---

maintenance/Rector/MockGrabyResponseRector.php

This now works properly thanks to https://github.com/rectorphp/rector-src/pull/6756

maintenance/Rector/MockGrabyResponseRector: Remove __DIR__ hack

---

src/SiteConfig/BuiltinConfigLinesProvider.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/ConfigLinesProvider.php
tests/SiteConfig/BuiltinConfigLinesProviderTest.php
tests/SiteConfig/ConfigBuilderTest.php

Abstract getting site config lines behind an interface, so that we can use other ways to get site configs.
More to come on wallabag side

Introduce config lines provider
