j0k3r/graby

composer.json

I had the following error : 
License "AGPLv3" is not a valid SPDX license identifier, see http://www.spdx.org/licenses/ if you use an open license.

Change syntax of licence

---

README.md
src/Extractor/HttpClient.php
src/Graby.php
tests/Extractor/HttpClientTest.php
tests/GrabyTest.php

graby won't throw exception anymore in case of error.
It will return the http status code with other information instead.
Fix #13

Return http status code

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php
tests/GrabyTest.php

By default, Guzzle send a request with option `CURLOPT_ENCODING` empty. It means, the server will answer with a plain content instead of gzipped content.
So we don't need to decode it.

Remove gzip decode, it's done on the request

---

src/Graby.php
tests/GrabyTest.php

The current url was used for each new page instead of the extracted one.

Fix bad url for multipage

---

src/Extractor/HttpClient.php
src/Graby.php
tests/Extractor/HttpClientTest.php

Changes the guzzle call to use the default cookie settings.
Also set the default guzzle client to accept cookies by default.
This allows customization of the guzzle client's cookies handling by providing a custom one with a CookieJar.

Use default guzzle cookies settings

---

src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php

> Required by wallabag's site login support.
Adds new settings that cover login to a site.
- `requires_login`: boolean, indicates if the site requires login or not (default: false)
- `not_logged_in_xpath`: string, xpath query for an element in articles pages indicating that login is needed
- `login_uri`: string, the uri to which login data must be POSTed
- `login_username_field`: string, name of the username field in the form
- `login_password_field`: string, name of the password field in the form
- `login_extra_fields`: hash of form field => field value to POST with the login form

Added login settings support

---

src/Extractor/ContentExtractor.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php

> Type: refactoring
> Backward compatible: yes
Moves the logic used in `ContentExtractor::buildSiteConfig()` to a new method in the `ContentBuilder`. I have left the HostFingerPrint part in the ContentExtractor, as I'm not 100% sure what it does (feedback welcome).
This change makes it possible to build site config objects from anywhere using the host name, as done by http://github.com/wallabag/wallabag in the site login feature PR.

Refactored the ContentBuilder out of the ContentExtractor

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php

When the body contains only one node (like `<p>content</p>`), `->firstChild` is null.
/see https://github.com/wallabag/wallabag/issues/1661

Fix a non-object in some case

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

Some meta can be generated with simple quote too, previous fingerprints regex doesn't handle them.
A Blogger website with that meta wasn't detected.
```html
<meta content='blogger' name='generator'/>
```

Fingerprints now handle simple quote

---

src/Ring/Client/SafeCurlHandler.php
tests/GrabyFunctionalTest.php

For example, this `index.php?article49/commandes-de-base` became `index.php?article49%2Fcommandes-de-base` which can generate an endless 301.
This should fix https://github.com/wallabag/wallabag/issues/1888 & https://github.com/wallabag/wallabag/issues/1897

Avoid sending encoded query string

---

src/Extractor/HttpClient.php
src/Graby.php
tests/GrabyTest.php

It'll avoid sending a huge amount of data.
Also don't truncate body for escaped fragment check  …
Some blogger website use data:uri image as og:image, so the body is huge and 4000 chars isn't enough to get the fragment meta.
We'll later if we can avoid sending the whole body.
Should fix https://github.com/wallabag/wallabag/issues/803

Avoid data:image in open graph data

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

Found in https://github.com/wallabag/wallabag/issues/2269
Image from [www.outsideonline.com](http://www.outsideonline.com/2108066/emerald-citys-velo-thieves-have-problem-bike-batman) are lazyloaded using `data-original` instead of `data-src` or `data-lazy-src`:
```html
```

Handle a new img lazyload

---

src/Graby.php
tests/GrabyFunctionalTest.php

Converting them to UTF8 using forceutf8 doesn’t work.
In that case, we just don’t convert anything and it seems to works.
Should fix https://github.com/wallabag/wallabag/issues/2135

Fix UTF16 content

---

src/Extractor/ContentExtractor.php
src/Graby.php

Avoid ConfigBuilder to build config multiple times.
Previously it was build in Graby and then rebuild in ContentExtractor.
Now, when it’s build in Graby, ContentExtractor will received cached config and will not rebuild config.

Share ConfigBuilder between classes

---

composer.json
src/Graby.php
tests/GrabyFunctionalTest.php

It was causing some troubles with (at least) chinese and korean page.
Content were completly unreadable.
So I decided to revert with the old way to convert content to utf8.
Let’s see.
This should fix https://github.com/wallabag/wallabag/issues/2387

Remove forceutf8

---

src/Extractor/HttpClient.php
src/Graby.php
tests/Extractor/HttpClientTest.php

We only remove conditional comments until we found the `<head>` tag.
They usually contains the `<html>` tag which we try to found and replace the last occurence with the whole conditional comments.
If no conditional comments are found, we do nothin.
Should fix https://github.com/wallabag/wallabag/issues/2150

Clean IE conditional comments

---

src/Extractor/HttpClient.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php
tests/fixtures/site_config/.wikipedia.org.txt

This PR adds the ability to graby to use user-agent provided in site configs instead of `default_ua` and `user_agents` from `HttpClient`.
http_header is extracted from site config and provided to `HttpClient#fetch()` and `HttpClient#getUserAgent()` to extract the user-agent, if any. In case of missing value we fall back to the original behavior: check host from `user_agents` or use `default_ua`.
There are some issues however, at this time:
* ~~`default_ua` is not used anymore as long as a `http_header(user-agent)` is currently provided in `global.txt`. A solution could be to ignore the user-agent provided by global, any thoughts?~~
* `HttpClient` does not have access to SiteConfig, some tests began to fail because of the deletion of default `user_agents` array (e9f2981e573). I fixed them …

Add support of http_header property in site config

---

src/Extractor/HttpClient.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php
tests/SiteConfig/ConfigBuilderTest.php

Following #61, this PR adds the support of `http_header(referer)` property from site config.
Fixes #62

Add support of referer from site config

---

tests/Extractor/HttpClientTest.php
tests/SiteConfig/ConfigBuilderTest.php

This PR is mainly cosmetic: it rewrites arguments of `testUserAgent` in camelCase and updates `testBuildFromArray` to include `http_header(user-agent)`.

Improve tests from #61

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

The regex doesn’t matche every case. And if it matches, it now check that the matching value isn’t empty (which was the case for `https://venngage.com/blog/hashtags-are-worthless/`)

Update regex for html IE conditional

---

src/Graby.php
tests/GrabyFunctionalTest.php
tests/fixtures/site_config/journaldugamer.com.txt

Sometimes, error like this raise:
> DOMDocument::importNode(): Couldn't fetch Readability\JSLikeHTMLElement
Should fix #71

Fix importNode error in some case

---

.travis.yml
README.md
composer.json
src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php

For the moment, we'll be able to add `pre_filters` & `post_filters` to Readability.
It'll ease the removal of content from the final client (like wallabag)
Should fix https://github.com/j0k3r/graby/issues/74

Add ability to add pre/post filters to Readability

---

composer.json

tecnickcom/tcpdf is not maintain anymore.
Developer has moved to a new library which is far from being stable atm.
Instead of keeping an unmaintain deps, the wallabag/core team forked the original repo to submit patch.
See https://github.com/wallabag/wallabag/issues/2930

Use wallabag/tcpdf

---

src/Graby.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php

Graby has a xss-filter parameter in the configuration but it was useless because the sanitized text was not re-used.

Fixed xss-filter part which was useless

---

src/Extractor/HttpClient.php
src/Graby.php
tests/GrabyTest.php

Since the response body is available, there is no need to re-fetch the resource again. Additionally, the PDF parser [does not handle errors when fetching files](https://github.com/smalot/pdfparser/blob/c20bfd40e3d7f40ff4083de5971b2a9e7a839dd5/src/Smalot/PdfParser/Parser.php#L72), so this also improves error handling. This is the brokenness I mentioned [here](https://github.com/j0k3r/graby/pull/80#issuecomment-287549743), the server returned 403 but PdfParser complained about being unable to parse.

Use parseContent method for parsing PDFs

---

src/Extractor/ContentExtractor.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php
tests/SiteConfig/ConfigBuilderTest.php

This PR adds back the support of date to extract the publication date of articles. Partially based on #22. 
Fixes #67

[WIP] Add support of date from site config

---

src/Graby.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php
tests/SiteConfig/ConfigBuilderTest.php

Since a previous fix (https://github.com/j0k3r/graby/pull/82), iframes were removed by htmLawed leaving them as `[embedded content]` only
Might fix https://github.com/j0k3r/f43.me/issues/133

Safe iframe

---

src/Extractor/ContentExtractor.php
tests/GrabyFunctionalTest.php
tests/fixtures/site_config/liberation.fr.txt

Following https://github.com/j0k3r/graby/pull/89
Multiple authors weren't retrieved.

Fix multiple authors

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

The plus symbols ('+') was replaced by a space character.
See https://github.com/wallabag/wallabag/issues/3002

Fix url extraction when url contains the symbol '+'

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

By convention, it seems that Angular website doesn't always handle escaped fragment to get full html page.
In fact, the website which used Angular with escaped fragment now handle the fragment meta: https://tempostorm.com/articles/the-singleton-special-when-to-oneoff:
```html
<meta name="fragment" content="!">
```
Might fix https://github.com/j0k3r/graby/issues/48

ng-controller should not trigger escaped fragment

---

src/Graby.php
tests/GrabyTest.php

Add ability to clean a given HTML content using same method as when fetching content from an url.
For example it'll allow wallabag to save content without fetching url (when using from a browser extension for example).
Code as been a refactored to move clean logic into a dedicated method.
Also, the method `handleMimeAction` is now more clear and less complex.
@tcitworld @nicosomb what crazy html content should I check for that particular case?
I've added some obvious xss using `<script>` tag but I think we can found more malicious HTML :skull_and_crossbones:

Ability to clean given HTML

---

src/Graby.php
tests/GrabyFunctionalTest.php

Keep only the og:image we found, which is usually the best one.
Should fix https://github.com/wallabag/wallabag/issues/3115

Take only the first og:image

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php

Some content fail to be requested (because they return a code 50x or 40x) but they content a response.
Some website doesn’t work as expected and return an error when they actually send the good content.
So if the exception contain a response, we’ll now try to retrieve content from it.
Will fix https://github.com/wallabag/wallabag/issues/3250

If request fail try to fetch content anyway

---

src/Extractor/HttpClient.php
src/SiteConfig/ConfigBuilder.php

Instead of a simple debug message when a content can’t be fetched because of a bad request (time out or whatever) it’s more interesting to log it as error so it’ll appear in the log file even in production.
We can see it more and more when a website can't be fetched in wallabag and most of the time it's because of a bad configuration on their side. So, to avoid forcing them to enable log, clear cache and retry, the `prod.log` file might now contains the error information we need.

Rise log level when catching exception

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php

JSON-LD schema is mostly used by Google to understand more easily what’s in the website page.
There is some precious information we can extract from here without parsing the whole document.
First try is using a regex to match the script tag because Readability remove all script from its dom.

 Retrieve information from JSON-LD schema 

---

.scrutinizer.yml
.travis.yml
README.md
tests/Extractor/HttpClientTest.php
tests/GrabyTest.php

- Convert hard coded Guzzle 5 test
- Update timeout in README, the full config might be at the end of the README
- Be Guzzle version agnostic
- Add a Travis build with Guzzle 6 (since Guzzle 5 is by default)

Agnostic Guzzle

---

README.md
UPGRADE-2.0.md
src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php

Parsing OpenGraph information is now perform in ContentExtract instead
of Graby. As well as JSON-LD.
These information are fetched before trying to extract information from
html using xpath & readability.
Information from xpath & readability override og & json-ld.
Also, some breaking changes from what Graby return:
- `all_headers` became `headers`
- `open_graph` no longer exist (see above)
- `content_type` no longer exist (check headers instead)

Use og & json-ld to improve results

---

README.md
src/Extractor/ContentExtractor.php

Instead of having custom condition for each case, move them in config and loop on each attribute.
It’ll ease adding new attributes in the future.

Move lazy load attributes to config

---

src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php
tests/SiteConfig/ConfigBuilderTest.php

This PR adds the support of strip_attr, a new site config option which was added in FTR 3.8[1].
`strip_attr` will remove attributes matching the XPath. E.g. `//*/@class`, `//img/@style`.
[1] http://blog.fivefilters.org/post/165712503277/full-text-rss-38

Add support of strip_attr

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

Hi,
On some sites, I had some duplicate authors (eg. https://www.lemonde.fr/pixels/article/2018/05/30/bloodstained-curse-of-the-moon-delicieux-jeu-de-vampires-a-la-mode-des-annees-1980_5307173_4408996.html). I fixed it.
Have a nice week-end.

Fix unique authors list

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

Previously the regex didn’t catch all comments.
It’s now really better.
Fix #142

Better remove conditional comment for IE

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

Remove all conditional comment wasn't the best idea.
Some of these are used to define which `<html>` tag will be used by the browser. We need to keep at least one of these tag because it can contains valuable information like the language of the page.
Following https://github.com/j0k3r/graby/pull/150

Keep the old way to remove conditional comment

---

src/Extractor/ContentExtractor.php

Sometime the query predication failed with:
```
PHP Warning:  DOMXPath::query(): Invalid predicate
```
The `@` remove the warning and we’ve added an extra check about what `query` returns.

Fix “Invalid predicate” error on DOMXPath::query

---

src/Extractor/HttpClient.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/HttpClientTest.php
tests/SiteConfig/ConfigBuilderTest.php

[Some site_config](https://github.com/fivefilters/ftr-site-config/search?p=1&q=http_header%28cookie%29&unscoped_q=http_header%28cookie%29) have a cookie defined (mostly for GDPR consent) but graby wasn't updated to support that.
It's not done.
You can add a cookie manually in a site config using:
```
http_header(Cookie): cookiename=cookievalue
```

Add support for cookie in site_config

---

src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php

Some JSON-LD information are bad because they aren’t related to the article of the website but to the website itself.
Fixes https://github.com/wallabag/wallabag/issues/3759

Add ability to skip getting data from json-ld

---

src/Extractor/HttpClient.php
tests/GrabyFunctionalTest.php
tests/fixtures/site_config/npr.org.txt

The first solution didn’t work.
Using the CookieParser from Guzzle and injecting cookies in the right place, solve the issue.
Related https://github.com/wallabag/wallabag/issues/3136#issuecomment-434609553

Fix cookies injection into request

---

composer.json
src/Extractor/HttpClient.php

After using an old version of Guzzle to parse cookie, which wasn’t included in prod deps but only on dev deps (because of php-coveralls) (see https://github.com/j0k3r/graby/pull/172), then explicitely required it and finally got a conflict with event dispatcher (see https://github.com/j0k3r/graby/pull/173), use a dedicated solution without a deps.
Pfiou.

Use own solution to parse cookie

---

src/Graby.php

I propose this regex modification to actually clean empty nodes before using php-readability and/or Tidy.
This regex specifically exclude the first group to be an `iframe` (which was the intention according to the comment), but allows the deletion of empty attribute-containing nodes.
With this modification, will be detected and deleted the following examples:
```html
<h2></h2>
<p></p>
<h2 class="align"></h2>
<head></head>
```
but not
```html
<iframe></iframe>
<iframe src="xxx.html"></iframe>
```
You can test it here: https://regex101.com/r/uWjsOc/1
It fixes https://github.com/wallabag/wallabag/issues/3730 and make https://github.com/j0k3r/php-readability/issues/39 closable (as I had no proof it was a _php-readability_ issue).

Update Graby.php (regex modification)

---

phpunit.xml

Mostly for the 7.1 build which fails because of:
The "PHPUnit_Framework_MockObject_Matcher_Parameters::verify()" method will require a new "PHPUnit_Framework_MockObject_Invocation $invocation" argument in the next major version of its parent class "PHPUnit_Framework_MockObject_Matcher_StatelessInvocation", not defining it is deprecated.

Avoid deprecated message to fail the build

---

src/Graby.php

The precedent regex couldn't detect if there was only "normal" spaces
inside empty nodes. I think some groups were wrongfully intertwined
sometime in the past.
You can check here to see examples/tests:
https://regex101.com/r/YdPShz/1/

Regex update to strip empty nodes containing spaces

---

src/Graby.php
src/SiteConfig/ConfigBuilder.php

The load is externalized into a dedicated public method so we can reload config files after a custom creation of a config file.
- Config files are loaded when the class is instancied.
- If we add a new file after, it won't be loaded.
- We'll need to manually reload config files
It’s usefull when we provide an interface to allow the user to define a custom site config (to test some rules for example)

Add ability to reload config files

---

src/Graby.php

Delete empty lines in retrieved HTML code to avoid runaway evaluation of empty node stripping regex on badly coded websites.

Fix wallabag#3825

---

src/Graby.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/GrabyTest.php
tests/SiteConfig/ConfigBuilderTest.php
tests/fixtures/site_config/timothysykes.com.txt

It was introduced in Full-Text RSS 3.5.
> XPath expression used to determine if the `single_page_link` rule gets evaluated or not.

Handle "if_page_contains" for "single_page_link"

---

.gitignore
src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php

Hello,
Here is my attempt at a better debug mode for Graby. The idea is to fully use the various levels of information possible that can be passed to the logger (`Logger::DEBUG` and `Logger::INFO`) to separate log messages. Graby's config is changed to `'debug' => false` to `'log_level' => false`, and expect `debug` or `info` as argument.
I chose the `Logger::INFO` level to store what was previously in the debug mode, as it is indeed information about the steps taken, without too much details. The `Logger::DEBUG` level stores in a separate log file `html.log` the data at various steps during the fetching/cleaning process. _Note that I put something to empty this file each time graby's called._
By default, nothing is stored ; if `'log_level' => 'info'`, only INFO messages are stored in …

Debug mode for graby

---

src/Extractor/ContentExtractor.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/GrabyTest.php
tests/fixtures/content/rollingstone.html
tests/fixtures/site_config/rollingstone.com.txt

`single_page_link` has priority over `next_page_link` when both are defined the site config file and `if_page_contains` rules are defined.
Problem appear when you want to fetch the homepage of `rollingstone.com` for example (yeah bad idea anyway). The source contains the `next_page_link` defined in [the site config](https://github.com/fivefilters/ftr-site-config/commits/7baf9d42bd05e5c20a41241b3c6e1693c975f21a/rollingstone.com.txt). But as graby doesn't handle `if_page_contains` for `next_page_link` it started to fetch endlessly all pages from rollingstone homepage. Gasp.
Following https://github.com/j0k3r/graby/pull/190

Handle "if_page_contains" for "next_page_link"

---

src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php

Ignore objects with type Organization, WebSite or Person. Also maintain
a list of values (only name) from these ignored objects to reject
similar values in other objects (e.g. a Periodical object with the name
of the WebSite).
Fixes https://github.com/wallabag/wallabag/issues/3878

Rework JsonLd extraction: ignore some objects and some names

---

src/Graby.php
tests/GrabyTest.php

Use `Graby::toggleImgNoReferrer(true)` in your client to automatically set
`referrerpolicy="no-referrer"` to all `img` tags.
Relates to https://github.com/wallabag/wallabag/issues/3889
Depends on https://github.com/fossar/HTMLawed/pull/3

Add support of referrerpolicy for img tags

---

src/Extractor/ContentExtractor.php

Hi there,
I added some info from the logger to get debug on JsonLd parsing.
Have a nice day.

Logger infos added for JsonLd parsing

---

src/SiteConfig/ConfigBuilder.php
tests/SiteConfig/ConfigBuilderTest.php

`find_string` & `replace_string` had special case when merging them.
But it failed when merging multiple times some site config.
Update it to a bit more complex solution to ensure `find_string` & `replace_string` aren't duplicated when merging config multiple times.
We can't perform an `array_unique` on these values (looks like fabrizio got the point years ago) mostly because `replace_string` can have same values, example:
```
find_string: <amp-img
replace_string: <img
find_string: <other-img
replace_string: <img
```
To fix that issue, we combine find & replace as key & value in one array, we merge them (so we can't have duplicates keys) and then rebuild find & replace string in the current config.
@fivefilters, you might be interested by applying that fix on FullTextRSS I think.
Fix …

Change the way to merge config for find & replace string

---

.travis.yml
src/Extractor/ContentExtractor.php
src/Graby.php
tests/Extractor/ContentExtractorTest.php

Instead of just validating the date is ok when parsing it, just convert it to the W3C format

Convert date to a known format

---

src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

We already handled meta refresh url but only when attributes are in the following order: `http-equiv` THEN `content`.
That PR will make the meta refresh url fetched works when they are in reverse: `content` THEN `http-equiv`
Fix https://github.com/wallabag/wallabag/issues/4259 & fix https://github.com/wallabag/android-app/issues/899

Handle meta refresh when attributes are reversed

---

.travis.yml
composer.json

This PR removes the explicit dependency to wallabag/tcpdf as graby does not use it itself and it may prevent wallabag from moving back to the former package (`tecnickcom/TCPDF`).

Remove the wallabag's fork of tcpdf

---

.editorconfig
.gitattributes
src/Graby.php
tests/GrabyTest.php
tests/fixtures/content/blog-oracle.html

Handle error using preg_* function when html is really too big

---

composer.json
src/Monolog/Formatter/GrabyFormatter.php
src/Monolog/Handler/GrabyHandler.php

Hi.
This PR allows you to use `graby` in the latest versions of Laravel, there is such `"monolog/monolog": "^2.0"` dependency in this beautiful framework
https://github.com/laravel/framework/blob/7.x/composer.json#L27
This will increase the reach of this package.

Support for Monolog v2

---

.gitignore
.travis.yml
composer.json
phpstan.neon
phpunit.xml
src/Extractor/ContentExtractor.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php
tests/Monolog/Formatter/GrabyFormatterTest.php
tests/Monolog/Handler/GrabyHandlerTest.php
tests/SiteConfig/ConfigBuilderTest.php

The lib is now fully tested with the lowest possible deps defined in `composer.json`.
I started that as we are now accepting Monolog 2.0. The library should still works with Monolog 1.
I found some flaws and raised some deps to make the library works again.
I've also upgraded PHPStan and convert some code to have less side effects.
Tests files are type hinted now.
The library isn't yet because it might BC. I'll have type hint on the library when jumping to the 3.0 release.

Define lowest working deps

---

composer.json

Allow installing `smalot/pdfparser` newer version

---

.editorconfig
.gitattributes
.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
.travis.yml
tests/GrabyFunctionalTest.php

Jump to GitHub Actions mostly because I found them most reliable these days (weeks?) than Travis.
Only keep Travis to run PHP 8 and allowed it to fail (because we can't achieve that using GitHub Actions (for now)).
Also comment the youtube oEmbed stuff because we got random failure for unknown reason.

Ditch Travis to use GitHub Actions

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

The extractor was incorrectly setting the value of data-srcset into the
src attribute, however srcset does not use the same format leading to
loading error with incorrect paths. Now data-srcset sets the value of
srcset which will let the browser to use paths of either src or srcset
attributes.
This PR may require new tests to ensure non-regression.
Here is an example with `https://www.numerama.com/sciences/661291-covid-19-le-modele-emmental-montre-aussi-pourquoi-la-desinformation-est-si-grave.html`: 
```
```
Fixes https://github.com/wallabag/wallabag/issues/4914

ContentExtractor: fix handling of data-srcset

---

phpstan.neon
src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/SiteConfig.php
tests/Extractor/ContentExtractorTest.php

Fixes #180
~Tests are missing for now~ Tests added, ready for review

Add support of `wrap_in`

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
README.md
UPGRADE.md
composer.json
phpstan.neon
phpunit.xml
src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
src/Graby.php
src/HttpClient/Plugin/CookiePlugin.php
src/HttpClient/Plugin/History.php
src/Monolog/Handler/GrabyHandler.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/ContentExtractorTest.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php

The old `preg_replace` call incorrectly removed the `?` of the query string
section which could lead to things like this:
`http://example.com/foo?utm_source=a&var=value` =>
`http://example.com/foo&var=value`

HttpClient: refactor the way we clean utm_ query params

---

src/Extractor/ContentExtractor.php
src/SiteConfig/ConfigBuilder.php

- PHP Warning:  array_combine(): Both parameters should have an equal number
- PHP Warning:  DOMDocument::saveXML(): unknown encoding
- PHP Fatal error:  Uncaught TypeError: Typed property Graby\\Extractor\\ContentExtractor::$title must be string or null
issue - #278

Fix PHP Error/Warnning

---

src/SiteConfig/ConfigBuilder.php
tests/GrabyFunctionalTest.php

For example, when user wants to replace a string with nothing, `replace_string:` will be used and shouldn't be skipped.
Also, adding more tests regarding [previous PR](https://github.com/j0k3r/graby/pull/279).

Ensure empty value from `site_config` are kept

---

src/SiteConfig/ConfigBuilder.php
tests/SiteConfig/ConfigBuilderTest.php

That validation is performed in `parseLines` so the size of them can't mismatch when merging configuration for example.
A warning log is raised in case of mismatch.
Following https://github.com/j0k3r/graby/pull/279#discussion_r780230930
Poke @jtojnar

Ensure `find_string` & `replace_string` size are equal

---

README.md
maintenance/Rector/MockGrabyResponseRector.php
phpunit.xml
src/Extractor/ContentExtractor.php
src/Extractor/ContentExtractorConfig.php
src/Extractor/HttpClient.php
src/Extractor/HttpClientConfig.php
src/Graby.php
src/GrabyConfig.php
src/OptionsResolver/ArrayStringOptionsTrait.php
src/SiteConfig/ConfigBuilder.php
src/SiteConfig/ConfigBuilderConfig.php
tests/GrabyTest.php

Mostly to enforce type of each parameter of a config.
Also, enforce type for the input configuration using `setAllowedTypes`.
See https://github.com/j0k3r/graby/pull/283#pullrequestreview-849144036
Is it something like that you were talking about @jtojnar?

Convert configuration to Value Object

---

README.md
src/Extractor/ContentExtractor.php
src/Extractor/ContentExtractorConfig.php

Some resources like Gamespot.com have VideoGame JsonLD objects that available on the page and because they are last, they rewrite correct datatime with incorrect one.
Example: 
https://www.gamespot.com/articles/nvidia-rtx-3090-3080-3070-gpu-all-specs-prices-and-release-dates-detailed/1100-6481673/
p.s Maybe there is a good idea to make this list customizable?

Add `VideoGame` JsonLD type to exceptions

---

README.md
src/Graby.php
tests/GrabyTest.php

fetchContent() now accepts an optional parameter, prefetchedContent, which
can contain the content of a page that was fetched outside of Graby.
If we take the example of Wallabag it gives the ability to send the
content of a page (_through a browser extension for example_) without
making network calls to fetch the actual page.

Add ability to process prefetched content

---

src/Graby.php

Empty td and th must be kept to prevent any layout breakage, e.g.:
``` html
<table>
<tr>
<td></td>
<td>Header</td>
</tr>
<tr>
<td>Foo</td>
<td>Bar</td>
</tr>
</table>
```

Graby: keep empty td and th elements

---

composer.json
maintenance/Rector/MockGrabyResponseRector.php
maintenance/rector.php
phpstan.neon

Currently broken for some reason:
If I revert the test fixtures, `composer rector` is no longer able to add them with Rector ≥ 0.13.1. It works with 0.13.0 and older. I do not see anything suspicious in the changes though https://github.com/rectorphp/rector-src/compare/0.13.0...0.13.1.
Opened https://github.com/rectorphp/rector/issues/7231.

rector: Update for latest version

---

composer.json

This constraint was introduced in
https://github.com/j0k3r/graby/commit/d8f93d915e784fb130e9b4e520e66e66d117dbdf
This is required for selfoss to use the latest version after https://github.com/fossar/selfoss/pull/1392
Partly fixes https://github.com/j0k3r/graby/issues/298

[2.x] dependencies: allow installing guzzlehttp/psr7 2.0

---

src/Extractor/ContentExtractor.php

This was tripping up selfoss:
date_parse(): Passing null to parameter #1 ($datetime) of type string is deprecated
[vendor/j0k3r/graby/src/Extractor/ContentExtractor.php:722]
[vendor/j0k3r/graby/src/Extractor/ContentExtractor.php:722] date_parse()
[vendor/j0k3r/graby/src/Extractor/ContentExtractor.php:541] Graby\Extractor\ContentExtractor->validateDate()
[vendor/j0k3r/graby/src/Graby.php:374] Graby\Extractor\ContentExtractor->process()
[vendor/j0k3r/graby/src/Graby.php:181] Graby\Graby->doFetchContent()
[src/spouts/rss/fulltextrss.php:97] Graby\Graby->fetchContent()
[src/spouts/rss/fulltextrss.php:74] spouts\rss\fulltextrss->getFullContent()
[src/spouts/Item.php:117] spouts\rss\fulltextrss->spouts\rss\{closure}()
[workbench.php:112] spouts\Item->getContent()

ContentExtractor: Fix invalid argument type

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
composer.json
src/Extractor/HttpClient.php
src/Graby.php
src/SiteConfig/ConfigBuilder.php
tests/Extractor/HttpClientTest.php
tests/GrabyFunctionalTest.php
tests/GrabyTest.php

Long time without an update and it requires an update. Also:
- use `http_build_query` to rebuild the query instead of `Uri::withQueryValues` because the array from the filter method might contains array and it's not supported (reported by PHPStan and validated with a new test)
- fix deprecating of `\SimplePie_Misc`
Replace https://github.com/j0k3r/graby/pull/308

Fix CS & upgrade GitHub Actions

---

src/Extractor/ContentExtractor.php

The property was introduced in https://github.com/j0k3r/graby/commit/b5d8ad48c7d01505c53c80382ccf11f2acb90148 without reset method being made aware of it.
As a result, Graby might have returned an image from a previous item, when the Graby instance is re-used (like Wallabag does).
Ideally, we would create a fresh ContentExtractor for each URL to preempt issues like this.

ContentExtractor: clear image property on reset

---

src/Graby.php

HTML attributes can contain a spaces around the equal sign: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2
Fixes: https://github.com/j0k3r/graby/issues/302

Graby::convert2Utf8: Allow spaces around HTML attributes

---

composer.json
maintenance/Rector/MockGrabyResponseRector.php
phpstan.neon
src/Extractor/ContentExtractor.php
src/Graby.php
tests/GrabyTest.php

phpunit-bridge also creates a stable symlink:
https://github.com/symfony/phpunit-bridge/commit/7421104e7b4286463353b0fa70f9b59ba3dda9df

PHPStan: use predictable phpunit path

---

src/Extractor/ContentExtractor.php
tests/Extractor/ContentExtractorTest.php

- Drop incorrect and redundant phpdoc param hint.
- Terminate early on null so that we can drop later casts and null checks.
- Drop extra date verification, we can just catch an Exception when DateTime constructor cannot parse the date.
As a bonus, negative dates like `-0001-11-30T00:00:00+00:00` will be accepted.

ContentExtractor: simplify validateDate

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
phpunit.xml

Otherwise the date tests will fail locally, when user does not have timezone set.
Fixes: https://github.com/j0k3r/graby/issues/318

tests: Define timezone in PHPUnit config

---

composer.json
maintenance/Rector/Helpers/RecordingHttpClient.php
src/Extractor/HttpClient.php
src/Graby.php

The `psr-http/client-implementation` dependency appears to have been accidentally removed in ac5d7387c8579c5c4352f40afa2419a0ed7e5d67, while still being used.
Let’s switch to its spiritual successor `psr-http/client-implementation`, which is backed by PSR-18, and correctly declare the dependency.

composer: Declare dependency on psr/http-client-implementation

---

src/Extractor/ContentExtractor.php
src/Extractor/HttpClient.php
tests/Extractor/HttpClientTest.php

From the test added by this commit, the previous regex incorrectly removed the shown.jpg image. The new regex now keeps what would be normally shown by a browser.
It should be noted that, according to regex101.com this instruction comes at a cost three times higher that before (~1,200 iterations in place of ~400)
Fixes https://github.com/wallabag/wallabag/issues/6828
**This must be backported into release/2.x for wallabag**

Improve regex used to remove conditional comments in HTML

---

composer.json
tests/GrabyTest.php

Before 2.8.0 release, pdfparser added a space at roughly the 51th character,
incorrectly breaking some words:
Verdana : Nullam hendrerit ante sed risus luctus el ementum. Morbi consectetur <br />\n
et diam sed dignissim. Sed a erat metus. Mauris a u ltrices velit. Aenean laoreet <br />\n
lectus nisi, tincidunt auctor nunc dictum at. Pelle ntesque at enim ac arcu mattis <br />\n
pellentesque et et lectus. Pellentesque in augue ip sum. Vivamus sapien lorem, <br />\n
semper auctor ligula sit amet, aliquam imperdiet mi . Maecenas in neque in tellus <br />\n
sagittis feugiat ac non dolor. Ut adipiscing erat a c tortor fringilla, in lobortis orci <br />\n
gravida. Praesent vulputate neque ac nibh elementum  tempor. Etiam tincidunt <br />\n
aliquam libero, ut faucibus justo sodales sed. Aene an …

tests: Fix pdf test after pdfparser 2.8.0 bump

---

composer.json
src/Graby.php

Targeting 2.x as this is the version used by wallabag for now, and I want to remove an abandoned package.

Replace Punycode by Symfony polyfill

---

src/Extractor/ContentExtractor.php
src/Graby.php
tests/GrabyFunctionalTest.php
tests/fixtures/content/https___www.xataka.com_movilidad_coches-vendidos-2023-2024-espana.html

When page has an article body specified in JSON-LD, the HTML fragment is passed to `DOMDocument::loadHTML`.
`DOMDocument` will parse a HTML document as ISO-8859-1, unless the document contains an XML encoding declaration or HTML meta tag setting character set.
https://stackoverflow.com/a/39148511/160386
JSON-LD typically does not contain `meta[charset]` tag so we need to add it ourselves.
At this point the input should already be in UTF-8, as we convert all inputs to that encoding everywhere except in `Graby::cleanupHtml`. There we will clarify the requirement in doc comment.
Fixes: https://github.com/j0k3r/graby/issues/359

ContentExtractor: Fix encoding in JSON-LD

---

composer.json
src/Graby.php

When installing Graby as a dependency in another project (e.g. Wallabag), it produces this output.
```
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
```
The [3.0 release](https://github.com/j0k3r/httplug-ssrf-plugin/releases/tag/v3.0.0) `j0k3r/httplug-ssrf-plugin` implemented the change suggested above.
However, Graby currently requires `j0k3r/httplug-ssrf-plugin:^2.0`, which prevents it from making use of the above change.
This PR modifies the version requirements in `composer.json` to allow Graby to use either 2.x or 3.x of `j0k3r/httplug-ssrf-plugin` depending on the runtime environment.

Modify `composer.json` to allow `j0k3r/httplug-ssrf-plugin:^3.0`

---

.github/workflows/continuous-integration.yml
README.md
UPGRADE-2.0.md
composer.json
phpstan.neon
tests/Extractor/HttpClientTest.php

Looks like Guzzle conflicts with `j0k3r/httplug-ssrf-plugin` v3:
```
Problem 1
- Root composer.json requires php-http/guzzle5-adapter * -> satisfiable by php-http/guzzle5-adapter[dev-master, v0.1.0, ..., v0.6.0, v1.0.0, v1.0.1, 2.0.0, 2.0.x-dev].
- guzzlehttp/guzzle[5.1.0, ..., 5.2.0] require guzzlehttp/ringphp ~1.0 -> satisfiable by guzzlehttp/ringphp[1.0.0, ..., 1.1.x-dev].
- guzzlehttp/guzzle[5.3.0, ..., 5.3.1] require guzzlehttp/ringphp ^1.1 -> satisfiable by guzzlehttp/ringphp[1.1.0, 1.1.1, 1.1.x-dev].
- guzzlehttp/guzzle[5.3.2, ..., 5.3.x-dev] require react/promise ^2.2 -> found react/promise[v2.2.0, ..., 2.x-dev] but these were not loaded, likely because it conflicts with another require.
- guzzlehttp/ringphp[1.0.0, ..., 1.1.x-dev] require react/promise ~2.0 -> found …
```

Jump to Codecov & Remove Guzzle 5
